artifact_location: /home/mateo/Escritorio/Proyectos/mlops-zoomcamp/02-experiment-traking/02-experiment-traking/mlflow.db/0
creation_time: 1717004043764
experiment_id: '0'
last_update_time: 1717004043764
lifecycle_stage: active
name: Default
