artifact_uri: /home/mateo/Escritorio/Proyectos/mlops-zoomcamp/02-experiment-traking/02-experiment-traking/mlflow.db/492000004112917738/5cbf862ff9a9479e88ba84ac4c05f882/artifacts
end_time: null
entry_point_name: ''
experiment_id: '492000004112917738'
lifecycle_stage: active
run_id: 5cbf862ff9a9479e88ba84ac4c05f882
run_name: suave-eel-816
run_uuid: 5cbf862ff9a9479e88ba84ac4c05f882
source_name: ''
source_type: 4
source_version: ''
start_time: 1717004199416
status: 1
tags: []
user_id: mateo
